### ISSUE TITLE
ERROR	 (HttpError): Not Found

### ISSUE THREAD

**Issue by mithro** [mithro/autolabeler#60]
The current app deployment is getting the following error;
```
ERROR	 (HttpError): Not Found
    HttpError: Not Found
        at /rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/@octokit/request/5.4.10/node_modules/@octokit/request/dist-node/index.js:66:23
        at processTicksAndRejections (internal/process/task_queues.js:88:5)
        at async sendRequestWithRetries (/rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/@octokit/auth-app/2.10.2/node_modules/@octokit/auth-app/dist-node/index.js:440:12)
        at async Job.doExecute (/rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/bottleneck/2.19.5/node_modules/bottleneck/light.js:405:18)
```

**Comment by mithro** [comment]
```
    HttpError: Not Found
        at /rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/@octokit/request/5.4.10/node_modules/@octokit/request/dist-node/index.js:66:23
        at processTicksAndRejections (internal/process/task_queues.js:88:5)
        at async sendRequestWithRetries (/rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/@octokit/auth-app/2.10.2/node_modules/@octokit/auth-app/dist-node/index.js:440:12)
        at async Job.doExecute (/rbd/pnpm-volume/8f9a4cf4-b57a-45cf-93f2-37bc9eadfd05/node_modules/.registry.npmjs.org/bottleneck/2.19.5/node_modules/bottleneck/light.js:405:18)
event: {
    id: "780a27e0-2dc9-11eb-9033-3d3c5fca9f93"
    name: "pull_request"
    payload: {
      "action": "synchronize",
      "number": 59,
      "pull_request": {
        "url": "https://api.github.com/repos/mithro/autolabeler/pulls/59",
        "id": 525968425,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTI1OTY4NDI1",
        "html_url": "https://github.com/mithro/autolabeler/pull/59",
        "diff_url": "https://github.com/mithro/autolabeler/pull/59.diff",
        "patch_url": "https://github.com/mithro/autolabeler/pull/59.patch",
        "issue_url": "https://api.github.com/repos/mithro/autolabeler/issues/59",
        "number": 59,
        "state": "open",
        "locked": false,
        "title": "Testing...",
        "user": {
          "login": "mithro",
          "id": 21212,
          "node_id": "MDQ6VXNlcjIxMjEy",
          "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/mithro",
          "html_url": "https://github.com/mithro",
          "followers_url": "https://api.github.com/users/mithro/followers",
          "following_url": "https://api.github.com/users/mithro/following{/other_user}",
          "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
          "organizations_url": "https://api.github.com/users/mithro/orgs",
          "repos_url": "https://api.github.com/users/mithro/repos",
          "events_url": "https://api.github.com/users/mithro/events{/privacy}",
          "received_events_url": "https://api.github.com/users/mithro/received_events",
          "type": "User",
          "site_admin": false
        },
        "body": "",
        "created_at": "2020-11-23T20:13:19Z",
        "updated_at": "2020-11-23T20:21:29Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": "255c46efc5db48efad8bc774a8dc5b395b3439b8",
        "assignee": null,
        "assignees": [],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [],
        "milestone": null,
        "draft": false,
        "commits_url": "https://api.github.com/repos/mithro/autolabeler/pulls/59/commits",
        "review_comments_url": "https://api.github.com/repos/mithro/autolabeler/pulls/59/comments",
        "review_comment_url": "https://api.github.com/repos/mithro/autolabeler/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/mithro/autolabeler/issues/59/comments",
        "statuses_url": "https://api.github.com/repos/mithro/autolabeler/statuses/bc27cf3c52771bbc231d0686f0c7ff737025739a",
        "head": {
          "label": "mithro:test",
          "ref": "test",
          "sha": "bc27cf3c52771bbc231d0686f0c7ff737025739a",
          "user": {
            "login": "mithro",
            "id": 21212,
            "node_id": "MDQ6VXNlcjIxMjEy",
            "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mithro",
            "html_url": "https://github.com/mithro",
            "followers_url": "https://api.github.com/users/mithro/followers",
            "following_url": "https://api.github.com/users/mithro/following{/other_user}",
            "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
            "organizations_url": "https://api.github.com/users/mithro/orgs",
            "repos_url": "https://api.github.com/users/mithro/repos",
            "events_url": "https://api.github.com/users/mithro/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mithro/received_events",
            "type": "User",
            "site_admin": false
          },
          "repo": {
            "id": 97883709,
            "node_id": "MDEwOlJlcG9zaXRvcnk5Nzg4MzcwOQ==",
            "name": "autolabeler",
            "full_name": "mithro/autolabeler",
            "private": false,
            "owner": {
              "login": "mithro",
              "id": 21212,
              "node_id": "MDQ6VXNlcjIxMjEy",
              "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/mithro",
              "html_url": "https://github.com/mithro",
              "followers_url": "https://api.github.com/users/mithro/followers",
              "following_url": "https://api.github.com/users/mithro/following{/other_user}",
              "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
              "organizations_url": "https://api.github.com/users/mithro/orgs",
              "repos_url": "https://api.github.com/users/mithro/repos",
              "events_url": "https://api.github.com/users/mithro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/mithro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/mithro/autolabeler",
            "description": "Add labels to Pull Requests based on matched file patterns",
            "fork": false,
            "url": "https://api.github.com/repos/mithro/autolabeler",
            "forks_url": "https://api.github.com/repos/mithro/autolabeler/forks",
            "keys_url": "https://api.github.com/repos/mithro/autolabeler/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/mithro/autolabeler/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/mithro/autolabeler/teams",
            "hooks_url": "https://api.github.com/repos/mithro/autolabeler/hooks",
            "issue_events_url": "https://api.github.com/repos/mithro/autolabeler/issues/events{/number}",
            "events_url": "https://api.github.com/repos/mithro/autolabeler/events",
            "assignees_url": "https://api.github.com/repos/mithro/autolabeler/assignees{/user}",
            "branches_url": "https://api.github.com/repos/mithro/autolabeler/branches{/branch}",
            "tags_url": "https://api.github.com/repos/mithro/autolabeler/tags",
            "blobs_url": "https://api.github.com/repos/mithro/autolabeler/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/mithro/autolabeler/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/mithro/autolabeler/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/mithro/autolabeler/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/mithro/autolabeler/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/mithro/autolabeler/languages",
            "stargazers_url": "https://api.github.com/repos/mithro/autolabeler/stargazers",
            "contributors_url": "https://api.github.com/repos/mithro/autolabeler/contributors",
            "subscribers_url": "https://api.github.com/repos/mithro/autolabeler/subscribers",
            "subscription_url": "https://api.github.com/repos/mithro/autolabeler/subscription",
            "commits_url": "https://api.github.com/repos/mithro/autolabeler/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/mithro/autolabeler/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/mithro/autolabeler/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/mithro/autolabeler/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/mithro/autolabeler/contents/{+path}",
            "compare_url": "https://api.github.com/repos/mithro/autolabeler/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/mithro/autolabeler/merges",
            "archive_url": "https://api.github.com/repos/mithro/autolabeler/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/mithro/autolabeler/downloads",
            "issues_url": "https://api.github.com/repos/mithro/autolabeler/issues{/number}",
            "pulls_url": "https://api.github.com/repos/mithro/autolabeler/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/mithro/autolabeler/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/mithro/autolabeler/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/mithro/autolabeler/labels{/name}",
            "releases_url": "https://api.github.com/repos/mithro/autolabeler/releases{/id}",
            "deployments_url": "https://api.github.com/repos/mithro/autolabeler/deployments",
            "created_at": "2017-07-20T22:37:34Z",
            "updated_at": "2020-11-23T19:53:04Z",
            "pushed_at": "2020-11-23T20:21:28Z",
            "git_url": "git://github.com/mithro/autolabeler.git",
            "ssh_url": "git@github.com:mithro/autolabeler.git",
            "clone_url": "https://github.com/mithro/autolabeler.git",
            "svn_url": "https://github.com/mithro/autolabeler",
            "homepage": null,
            "size": 80,
            "stargazers_count": 88,
            "watchers_count": 88,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 24,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 5,
            "license": {
              "key": "isc",
              "name": "ISC License",
              "spdx_id": "ISC",
              "url": "https://api.github.com/licenses/isc",
              "node_id": "MDc6TGljZW5zZTEw"
            },
            "forks": 24,
            "open_issues": 5,
            "watchers": 88,
            "default_branch": "master",
            "allow_squash_merge": true,
            "allow_merge_commit": true,
            "allow_rebase_merge": true,
            "delete_branch_on_merge": false
          }
        },
        "base": {
          "label": "mithro:master",
          "ref": "master",
          "sha": "a56874f03ec76fbce6e477c4c52367ae31f5e70b",
          "user": {
            "login": "mithro",
            "id": 21212,
            "node_id": "MDQ6VXNlcjIxMjEy",
            "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mithro",
            "html_url": "https://github.com/mithro",
            "followers_url": "https://api.github.com/users/mithro/followers",
            "following_url": "https://api.github.com/users/mithro/following{/other_user}",
            "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
            "organizations_url": "https://api.github.com/users/mithro/orgs",
            "repos_url": "https://api.github.com/users/mithro/repos",
            "events_url": "https://api.github.com/users/mithro/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mithro/received_events",
            "type": "User",
            "site_admin": false
          },
          "repo": {
            "id": 97883709,
            "node_id": "MDEwOlJlcG9zaXRvcnk5Nzg4MzcwOQ==",
            "name": "autolabeler",
            "full_name": "mithro/autolabeler",
            "private": false,
            "owner": {
              "login": "mithro",
              "id": 21212,
              "node_id": "MDQ6VXNlcjIxMjEy",
              "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/mithro",
              "html_url": "https://github.com/mithro",
              "followers_url": "https://api.github.com/users/mithro/followers",
              "following_url": "https://api.github.com/users/mithro/following{/other_user}",
              "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
              "organizations_url": "https://api.github.com/users/mithro/orgs",
              "repos_url": "https://api.github.com/users/mithro/repos",
              "events_url": "https://api.github.com/users/mithro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/mithro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/mithro/autolabeler",
            "description": "Add labels to Pull Requests based on matched file patterns",
            "fork": false,
            "url": "https://api.github.com/repos/mithro/autolabeler",
            "forks_url": "https://api.github.com/repos/mithro/autolabeler/forks",
            "keys_url": "https://api.github.com/repos/mithro/autolabeler/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/mithro/autolabeler/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/mithro/autolabeler/teams",
            "hooks_url": "https://api.github.com/repos/mithro/autolabeler/hooks",
            "issue_events_url": "https://api.github.com/repos/mithro/autolabeler/issues/events{/number}",
            "events_url": "https://api.github.com/repos/mithro/autolabeler/events",
            "assignees_url": "https://api.github.com/repos/mithro/autolabeler/assignees{/user}",
            "branches_url": "https://api.github.com/repos/mithro/autolabeler/branches{/branch}",
            "tags_url": "https://api.github.com/repos/mithro/autolabeler/tags",
            "blobs_url": "https://api.github.com/repos/mithro/autolabeler/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/mithro/autolabeler/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/mithro/autolabeler/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/mithro/autolabeler/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/mithro/autolabeler/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/mithro/autolabeler/languages",
            "stargazers_url": "https://api.github.com/repos/mithro/autolabeler/stargazers",
            "contributors_url": "https://api.github.com/repos/mithro/autolabeler/contributors",
            "subscribers_url": "https://api.github.com/repos/mithro/autolabeler/subscribers",
            "subscription_url": "https://api.github.com/repos/mithro/autolabeler/subscription",
            "commits_url": "https://api.github.com/repos/mithro/autolabeler/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/mithro/autolabeler/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/mithro/autolabeler/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/mithro/autolabeler/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/mithro/autolabeler/contents/{+path}",
            "compare_url": "https://api.github.com/repos/mithro/autolabeler/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/mithro/autolabeler/merges",
            "archive_url": "https://api.github.com/repos/mithro/autolabeler/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/mithro/autolabeler/downloads",
            "issues_url": "https://api.github.com/repos/mithro/autolabeler/issues{/number}",
            "pulls_url": "https://api.github.com/repos/mithro/autolabeler/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/mithro/autolabeler/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/mithro/autolabeler/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/mithro/autolabeler/labels{/name}",
            "releases_url": "https://api.github.com/repos/mithro/autolabeler/releases{/id}",
            "deployments_url": "https://api.github.com/repos/mithro/autolabeler/deployments",
            "created_at": "2017-07-20T22:37:34Z",
            "updated_at": "2020-11-23T19:53:04Z",
            "pushed_at": "2020-11-23T20:21:28Z",
            "git_url": "git://github.com/mithro/autolabeler.git",
            "ssh_url": "git@github.com:mithro/autolabeler.git",
            "clone_url": "https://github.com/mithro/autolabeler.git",
            "svn_url": "https://github.com/mithro/autolabeler",
            "homepage": null,
            "size": 80,
            "stargazers_count": 88,
            "watchers_count": 88,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 24,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 5,
            "license": {
              "key": "isc",
              "name": "ISC License",
              "spdx_id": "ISC",
              "url": "https://api.github.com/licenses/isc",
              "node_id": "MDc6TGljZW5zZTEw"
            },
            "forks": 24,
            "open_issues": 5,
            "watchers": 88,
            "default_branch": "master",
            "allow_squash_merge": true,
            "allow_merge_commit": true,
            "allow_rebase_merge": true,
            "delete_branch_on_merge": false
          }
        },
        "_links": {
          "self": {
            "href": "https://api.github.com/repos/mithro/autolabeler/pulls/59"
          },
          "html": {
            "href": "https://github.com/mithro/autolabeler/pull/59"
          },
          "issue": {
            "href": "https://api.github.com/repos/mithro/autolabeler/issues/59"
          },
          "comments": {
            "href": "https://api.github.com/repos/mithro/autolabeler/issues/59/comments"
          },
          "review_comments": {
            "href": "https://api.github.com/repos/mithro/autolabeler/pulls/59/comments"
          },
          "review_comment": {
            "href": "https://api.github.com/repos/mithro/autolabeler/pulls/comments{/number}"
          },
          "commits": {
            "href": "https://api.github.com/repos/mithro/autolabeler/pulls/59/commits"
          },
          "statuses": {
            "href": "https://api.github.com/repos/mithro/autolabeler/statuses/bc27cf3c52771bbc231d0686f0c7ff737025739a"
          }
        },
        "author_association": "OWNER",
        "active_lock_reason": null,
        "merged": false,
        "mergeable": null,
        "rebaseable": null,
        "mergeable_state": "unknown",
        "merged_by": null,
        "comments": 1,
        "review_comments": 0,
        "maintainer_can_modify": false,
        "commits": 1,
        "additions": 1,
        "deletions": 0,
        "changed_files": 1
      },
      "before": "19d513c535ed85324f09ea6254f238a5b5c7abb1",
      "after": "bc27cf3c52771bbc231d0686f0c7ff737025739a",
      "repository": {
        "id": 97883709,
        "node_id": "MDEwOlJlcG9zaXRvcnk5Nzg4MzcwOQ==",
        "name": "autolabeler",
        "full_name": "mithro/autolabeler",
        "private": false,
        "owner": {
          "login": "mithro",
          "id": 21212,
          "node_id": "MDQ6VXNlcjIxMjEy",
          "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/mithro",
          "html_url": "https://github.com/mithro",
          "followers_url": "https://api.github.com/users/mithro/followers",
          "following_url": "https://api.github.com/users/mithro/following{/other_user}",
          "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
          "organizations_url": "https://api.github.com/users/mithro/orgs",
          "repos_url": "https://api.github.com/users/mithro/repos",
          "events_url": "https://api.github.com/users/mithro/events{/privacy}",
          "received_events_url": "https://api.github.com/users/mithro/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/mithro/autolabeler",
        "description": "Add labels to Pull Requests based on matched file patterns",
        "fork": false,
        "url": "https://api.github.com/repos/mithro/autolabeler",
        "forks_url": "https://api.github.com/repos/mithro/autolabeler/forks",
        "keys_url": "https://api.github.com/repos/mithro/autolabeler/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mithro/autolabeler/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mithro/autolabeler/teams",
        "hooks_url": "https://api.github.com/repos/mithro/autolabeler/hooks",
        "issue_events_url": "https://api.github.com/repos/mithro/autolabeler/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mithro/autolabeler/events",
        "assignees_url": "https://api.github.com/repos/mithro/autolabeler/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mithro/autolabeler/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mithro/autolabeler/tags",
        "blobs_url": "https://api.github.com/repos/mithro/autolabeler/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mithro/autolabeler/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mithro/autolabeler/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mithro/autolabeler/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mithro/autolabeler/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mithro/autolabeler/languages",
        "stargazers_url": "https://api.github.com/repos/mithro/autolabeler/stargazers",
        "contributors_url": "https://api.github.com/repos/mithro/autolabeler/contributors",
        "subscribers_url": "https://api.github.com/repos/mithro/autolabeler/subscribers",
        "subscription_url": "https://api.github.com/repos/mithro/autolabeler/subscription",
        "commits_url": "https://api.github.com/repos/mithro/autolabeler/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mithro/autolabeler/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mithro/autolabeler/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mithro/autolabeler/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mithro/autolabeler/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mithro/autolabeler/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mithro/autolabeler/merges",
        "archive_url": "https://api.github.com/repos/mithro/autolabeler/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mithro/autolabeler/downloads",
        "issues_url": "https://api.github.com/repos/mithro/autolabeler/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mithro/autolabeler/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mithro/autolabeler/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mithro/autolabeler/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mithro/autolabeler/labels{/name}",
        "releases_url": "https://api.github.com/repos/mithro/autolabeler/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mithro/autolabeler/deployments",
        "created_at": "2017-07-20T22:37:34Z",
        "updated_at": "2020-11-23T19:53:04Z",
        "pushed_at": "2020-11-23T20:21:28Z",
        "git_url": "git://github.com/mithro/autolabeler.git",
        "ssh_url": "git@github.com:mithro/autolabeler.git",
        "clone_url": "https://github.com/mithro/autolabeler.git",
        "svn_url": "https://github.com/mithro/autolabeler",
        "homepage": null,
        "size": 80,
        "stargazers_count": 88,
        "watchers_count": 88,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 24,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 5,
        "license": {
          "key": "isc",
          "name": "ISC License",
          "spdx_id": "ISC",
          "url": "https://api.github.com/licenses/isc",
          "node_id": "MDc6TGljZW5zZTEw"
        },
        "forks": 24,
        "open_issues": 5,
        "watchers": 88,
        "default_branch": "master"
      },
      "sender": {
        "login": "mithro",
        "id": 21212,
        "node_id": "MDQ6VXNlcjIxMjEy",
        "avatar_url": "https://avatars2.githubusercontent.com/u/21212?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mithro",
        "html_url": "https://github.com/mithro",
        "followers_url": "https://api.github.com/users/mithro/followers",
        "following_url": "https://api.github.com/users/mithro/following{/other_user}",
        "gists_url": "https://api.github.com/users/mithro/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mithro/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mithro/subscriptions",
        "organizations_url": "https://api.github.com/users/mithro/orgs",
        "repos_url": "https://api.github.com/users/mithro/repos",
        "events_url": "https://api.github.com/users/mithro/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mithro/received_events",
        "type": "User",
        "site_admin": false
      },
      "installation": {
        "id": 80633,
        "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uODA2MzM="
      }
    }
}
status: 404
headers: {
    access-control-allow-origin: "*"
    access-control-expose-headers: "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"
    connection: "close"
    content-encoding: "gzip"
    content-security-policy: "default-src 'none'"
    content-type: "application/json; charset=utf-8"
    date: "Mon, 23 Nov 2020 20:21:30 GMT"
    referrer-policy: "origin-when-cross-origin, strict-origin-when-cross-origin"
    server: "GitHub.com"
    status: "404 Not Found"
    strict-transport-security: "max-age=31536000; includeSubdomains; preload"
    transfer-encoding: "chunked"
    vary: "Accept-Encoding, Accept, X-Requested-With"
    x-content-type-options: "nosniff"
    x-frame-options: "deny"
    x-github-media-type: "github.v3; format=json"
    x-github-request-id: "8AA4:2411:4CAF10:83C940:5FBC19CA"
    x-ratelimit-limit: "5000"
    x-ratelimit-remaining: "4998"
    x-ratelimit-reset: "1606166489"
    x-ratelimit-used: "2"
    x-xss-protection: "1; mode=block"
}
request: {
    method: "GET"
    url: "https://api.github.com/repos/mithro/autolabeler/pulls//files?issue_number=59"
    headers: {
      "accept": "application/vnd.github.v3+json",
      "user-agent": "probot/10.17.2 octokit-core.js/3.2.1 Node.js/12.0.0 (linux; x64)",
      "authorization": "token [REDACTED]"
    }
    request: {}
}
```

**Comment by Gabitchov** [comment]
Good stuff to begin the investigation. Can you give me more detail about the way how the app is deployed(heroku or other)? Thanks

**Comment by mithro** [comment]
@Gabitchov It is deployed on https://glitch.com/ -- If you sign up to that I can probably give you direct access to the deployed version to play with...

**Comment by Gabitchov** [comment]
I signed up and you can probably find me with the same username @Gabitchov.

**Comment by Gabitchov** [comment]
I created to fix with a modification of the API call. I will check if there is a ticket open(about this broken api url) on the library used by the Probot framework.

**Comment by Gabitchov** [comment]
The solution of the issue was found here: https://github.com/probot/probot/issues/1375

**Comment by Gabitchov** [comment]
:tada: fixed :tada:
